version: '3.8'

services:
  cpp-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: cpp-docker-app
    restart: unless-stopped
    # Uncomment if you need to expose ports
    # ports:
    #   - "8080:8080"
    
    # Uncomment if you need volumes
    # volumes:
    #   - ./data:/app/data:ro
    
    # Environment variables
    environment:
      - APP_ENV=production
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # Example service for development with volume mounting
  cpp-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: cpp-docker-app-dev
    working_dir: /app
    volumes:
      - .:/app
    command: /bin/bash
    stdin_open: true
    tty: true
    profiles:
      - dev